FROM alpine:edge
MAINTAINER Simone Basso (bassosimone@gmail.com)
RUN apk add --update autoconf automake cmake g++ curl curl-dev file \
  git libevent-dev libmaxminddb-dev libtool linux-headers make ninja
